# yaml(*.yml)
#     yet another markup language
#     ??? ??? ??? ??
#
# ?? ??
#   # ? ??
#   ????
#      key: value     <- : ???? ??? ????? ?? ?
#
#   key:
#       key_1:
#           key_2:
#               key_3:
#                   ..
# ??
#   https://lejewk.github.io/yaml-syntax/

# ???? ??
server:
  port: 8080

# ?? ANSI ??
spring:
  output:
    ansi:
      enabled: always

  # datasource ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db907?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user907
    password: 1234

  # JPA ??
  jpa:
    show-sql: true # JPA?? ???? SQL ?? ??? ??
    properties:
      hibernate:
        format_sql: true # Query ? ?? ?? ????? ??(?? ???)
    hibernate:
      # DDL(create, alter, drop) ??? DB? ?? ??? ??? ? ??.
      # create: ?? ?????? ?? ???? ???? ?? ??
      # create-drop: ????? create ? ??? ??? ??, ?????? drop
      # none : production ???? ????? ??? none ?? ??.
      # update: DB???? ??? ????? ???? ????? ?? ??? ?? (ALTER). ??? ??? CREATE
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # ??? ?? ??? ???? ???.
